apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-extractor-api-hpa
  namespace: video-extractor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
